services:
  playwright-tests:
    build: .
    container_name: playwright-tests
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000" # Allure report UI
    environment:
      - NODE_ENV=development
  playwright-custom:
    build: .
    container_name: playwright-custom
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5001:5000" # Allure report UI
    environment:
      - NODE_ENV=development
      - PLAYWRIGHT_BROWSER=${PLAYWRIGHT_BROWSER}
      - PLAYWRIGHT_HEADLESS=${PLAYWRIGHT_HEADLESS}
      - PLAYWRIGHT_REPORTER=${PLAYWRIGHT_REPORTER}
